version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "s3-stack-vv"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1iwiph9sot5im"
s3_prefix = "s3-stack-vv"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
